name: CI Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Instalar dependencias
        run: npm install

      - name: Verificar instalación de Jest
        run: npx jest --version

      - name: Dar permisos a Jest
        run: chmod +x ./node_modules/.bin/jest || true

      - name: Ejecutar pruebas
        run: npx jest
